# Generated by Django 5.1.3 on 2025-12-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='g_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
