# Generated by Django 5.1.3 on 2025-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_member_g_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='d_sir',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='has_2002',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='has_2025',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
