# Generated by Django 5.1.3 on 2025-12-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_member_d_sir_member_has_2002_member_has_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='draft_sir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
