# Generated by Django 5.1.3 on 2026-01-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_member_draft_sir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='h_address',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
