# Generated by Django 5.1.3 on 2026-01-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_alter_house_h_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active_in_house',
            field=models.BooleanField(default=True),
        ),
    ]
