# Generated by Django 5.1.3 on 2026-01-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0007_member_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='original_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_members', to='Survey.house'),
        ),
    ]
