# Generated by Django 5.1.3 on 2026-01-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_member_original_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='Survey.house')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_links', to='Survey.member')),
            ],
            options={
                'unique_together': {('member', 'house')},
            },
        ),
    ]
