# Generated by Django 5.1.3 on 2026-01-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0009_memberhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNameVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ml', models.CharField(blank=True, max_length=200, null=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('source', models.CharField(choices=[('excel', 'Excel Import'), ('manual', 'Manual Entry'), ('system', 'System')], default='excel', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_variants', to='Survey.member')),
            ],
            options={
                'unique_together': {('member', 'normalized_name')},
            },
        ),
    ]
