# Generated by Django 5.1.3 on 2026-01-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0010_membernamevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernamevariant',
            name='guardian_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membernamevariant',
            name='guardian_ml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membernamevariant',
            name='member_name_en',
            field=models.CharField(default='', help_text='Original member name (cached)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membernamevariant',
            name='member_name_ml',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membernamevariant',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
