# Generated by Django 5.1.3 on 2026-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0011_membernamevariant_guardian_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
